name: Comment
on: pull_request
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #GITHUB CLIが利用する環境変数
jobs:
  comment:
  runs-on: ubuntu-latest
  permissions: #GITHUB_TOKENの権限を指定2
    pull-requests: write #プルリクエストの書き込みを許可
    contents: read # ソースコードの読み込みを許可
  steps:
    - uses: actions/checkout@v4
    - run: gh pr comment "${secrets.GITHUB_HEAD_REF}" --body "Hello, ${GITHUB_ACTOR}" # GitHub CLI用クレデンシャル
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #GITHub cli用クレデンシャル