name: Static analytics
on:
  pull_request:
    paths: ['./github/workflows/*/yml','.github/workflows/*.yaml']
defaults:
  run:
    shell: bash # ワークフローで使うシェルをまとめて指定する
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubunts-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run --rm -v "$(pwd)" -w "$(pwd)" rhysd/actionlint:latest